actor_hidden_dims: [256, 256]
critic_hidden_dims: [256, 256]

actor_lr: 0.0003
critic_lr: 0.0003
alpha_lr: 0.0003

actor_lr_milestones: [10000]
critic_lr_milestones: [10000]
alpha_lr_milestones: [10000]

actor_lr_gamma: 0.5
critic_lr_gamma: 0.5
alpha_lr_gamma: 0.5

discount_factor: 0.95

critic_target_update_freq: 1
critic_target_tau: 0.005

device: 'cuda'
max_steps_in_episode: 2500
max_episodes: 1000000

entropy_tuning: false
alpha: 0.2
alpha_lr_milestones: [10000]
alpha_lr_gamma: 0.99

replay_buffer_size: 1000000
batch_size: 256
grad_steps: 128

eval_freq: 3
eval_episodes: 10